use_frameworks!

platform :ios, '8.0'

target 'GMObjC_Example' do
  pod 'GMObjC', :path => '../'
  pod 'GMOpenSSL'

  target 'GMObjC_Tests' do
    inherit! :search_paths
    pod 'GMObjC', :path => '../'

    
  end
end
